In [1]:
import numpy as np

 ## 1. loop and conditioning

## ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
### 1-1. if

 #### Basic Format

In [2]:
x = 1
if x > 0 :
    print("positive")
elif x < 0 :
    print("negative")
else : 
    print("zero")

positive


 #### reduced format

In [3]:
print("positive") if x > 0 else print("not positive")

positive



### 1-2. For

 #### Basic Format

In [4]:
for i in range(5) :
    print(i)

0
1
2
3
4


In [5]:
for i in range(5,0,-1) :
    print(i)

5
4
3
2
1


 ##### Call by element

In [6]:
words = ['pineapple','apple', 'banana', 'strawberry','blueberry']
for i in words :
    print(i)

pineapple
apple
banana
strawberry
blueberry


In [7]:
samsung = {'name' : 'samsung', 'beta' : 1.35 , 'realized_return' : 0.09}
lg = {'name' :'lg', 'beta' : 1.25 , 'realized_return' : 0.0825}
kt = {'name' :'kt', 'beta' : 0.8 , 'realized_return' : 0.05}
stock_info = [samsung, lg, kt]
for i in stock_info :
    print(i['beta'])

1.35
1.25
0.8


 ##### Call by index

In [8]:
for i in range(len(words)) :
    print(words[i])

pineapple
apple
banana
strawberry
blueberry


 ##### Make list

In [9]:
apple_list = []
berry_list = []
etc_list = []
for i in words :
    if 'apple' in i.lower() :
        apple_list.append(i)
    elif 'berry' in i.lower() :
        berry_list.append(i)
    else :
        etc_list.append(i)

In [10]:
print(apple_list)
print(berry_list) 
print(etc_list)

['pineapple', 'apple']
['strawberry', 'blueberry']
['banana']


 ##### Make Dictionary

In [11]:
my_dict = {'apple' : 0, 'berry' : 0 , 'etc' : 0}
for i in words :
    if 'apple' in i.lower() :
        my_dict['apple'] = my_dict['apple'] + 1
    elif 'berry' in i.lower() :
        my_dict['berry'] = my_dict['berry'] + 1
    else :
        my_dict['etc'] = my_dict['etc'] + 1

 #### reduced format

In [12]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
[i for i in range(10) if i%2 == 1]

[1, 3, 5, 7, 9]

 #### enumerate and zip function

In [15]:
for n, i in enumerate(words) :
    print(n, i)

0 pineapple
1 apple
2 banana
3 strawberry
4 blueberry


In [16]:
name_lst = ['Samsung','LG','SKT','Apple']
Default_Prob = [0.01,0.05,0.03,0.001]
for a,b in zip(name_lst, Default_Prob) :
    print('name : ',a,' /  PD :',b)

name :  Samsung  /  PD : 0.01
name :  LG  /  PD : 0.05
name :  SKT  /  PD : 0.03
name :  Apple  /  PD : 0.001


 ### 1-3. While : 조건에 해당될 때만 반복한다. 
 
 (반복문을 끄고싶을 경우에는 위에 Jupyter창의 Kernel 밑에있는 ■를 누르고 그 오른쪽에  재시작 버튼을 누르면 됩니다.)

In [17]:
rndn = 0
while rndn != 5 :
    rndn = np.random.randint(0,8)
    print(rndn)

2
3
4
2
4
1
4
3
5


In [18]:
loop_switch = True 
rndn = 0
while loop_switch :
    rndn = np.random.randint(0,8) 
    print(rndn)
    if rndn == 5 :
        break

0
1
2
4
4
5


 ### 1-4. Stock Price Simulation (중요도 높음)

\begin{align}
S(T) = S_0 e^{ (r-\frac{\sigma^2}{2})T + \sigma \sqrt{T} \epsilon} \\
\epsilon \sim N(0,1)
\end{align}

In [19]:
import numpy as np
S0 = 100
r = 0.05
sigma = 0.15
T = 2
S_path = S0 * np.exp( (r-0.5*sigma**2) *T  +  sigma *np.sqrt(T) * np.random.normal(0,1) )
S_path

93.50040487094522

In [20]:
S_path_list = []
for i in range(100) :
    S_path = S0 * np.exp( (r-0.5**sigma) *T  +  sigma *np.sqrt(T) * np.random.normal(0,1) )
    S_path_list.append(S_path)

 ### 1-5. Function Reduced Format ( 중요도 낮음.)

In [21]:
square_function = lambda x : x ** 2
square_function(3)

9

In [22]:
temp_function = lambda x,y,z=1 : x+y-z
temp_function(3,2,8)

-3

In [23]:
temp_function(3,2)

4

In [24]:
lst = [i for i in range(10) if i%2 == 1]
temp_lambda2 = lambda x : x ** 2 - 1
list(map(temp_lambda2, lst))

[0, 8, 24, 48, 80]

## ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 
 ## 1-1 ~ 1-5 실습


### 문제 1. 

다음 변수를 이용하여 주식들이 CAPM 균형수익률을 감안했을 때 저평가되었는지 고평가되었는지 적정수준인지를 계산하시오.

rf = 0.02, 
rm = 0.07

samsung = {'name' : 'samsung', 'beta' : 1.35 , 'realized_return' : 0.09}

lg = {'name' :'lg', 'beta' : 1.25 , 'realized_return' : 0.825}

kt = {'name' :'kt', 'beta' : 0.8 , 'realized_return' : 0.05}

stock_info = [samsung, lg, kt]

In [25]:
rf, rm = 0.02, 0.07
samsung = {'name' : 'samsung', 'beta' : 1.35 , 'realized_return' : 0.09}
lg = {'name' :'lg', 'beta' : 1.25 , 'realized_return' : 0.0825}
kt = {'name' :'kt', 'beta' : 0.8 , 'realized_return' : 0.05}
stock_info = [samsung, lg, kt]

In [26]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################
for i in stock_info :
    capm_ret = rf + i['beta']*(rm-rf)
    realized_ret = i['realized_return']
    if capm_ret > realized_ret :
        over_or_under = '저평가'
    elif capm_ret < realized_ret :
        over_or_under = '고평가'
    else :
        over_or_under = '적정'
    print('균형수익률 = ' , rf + i['beta']*(rm-rf) ,'\n실제수익률 :',i['realized_return'], over_or_under , '\n--------------------')
#############################

균형수익률 =  0.08750000000000001 
실제수익률 : 0.09 고평가 
--------------------
균형수익률 =  0.0825 
실제수익률 : 0.0825 적정 
--------------------
균형수익률 =  0.06000000000000001 
실제수익률 : 0.05 저평가 
--------------------


 ### 문제 2.
 while 반복문을 사용하여 주가 시뮬레이션을 시행하고 그 결과를 리스트에 담으시오. 
 
 리스트에 계속 T시점의 시뮬레이션된 주가를 담고, 만약 시뮬레이션된 주가가 0시점 주가의 150%를 넘어가는 경우가 발생하면 반복문을 중단하시오.
 
 S0 = 100, sigma = 0.2, T = 1, r = 0.02
 
 

In [27]:
S0, sigma , T , r = 100, 0.2, 1, 0.02

In [28]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################
S_path_list = []
while True : 
    S_path = S0 * np.exp( (r-0.5*sigma**2) *T  +  sigma *np.sqrt(T) * np.random.normal(0,1) )
    S_path_list.append(S_path)
    if S_path/S0  > 1.5 :
        break

S_path_list
#############################

[96.06142471750826,
 114.04125459847252,
 100.44956254913646,
 89.04242495804114,
 82.1449648853132,
 93.00614922045976,
 71.33611408172939,
 127.03843734530274,
 83.26002859994811,
 113.15413696919656,
 77.91442583642086,
 102.33581634478894,
 109.00026313149691,
 97.34594412004799,
 76.11651667777542,
 109.72536216853163,
 98.80829322731546,
 77.81632034372625,
 127.31350232844612,
 88.58386707719939,
 104.762642350724,
 91.83501329790545,
 107.13271901803425,
 100.51580215443319,
 99.29395410569933,
 99.85680691868971,
 91.26272540638466,
 79.85097325190664,
 139.9313296624053,
 84.37906802567026,
 116.85441456425532,
 76.11372623899223,
 72.05579059541611,
 143.82869417432536,
 94.24564420611433,
 71.95251717242914,
 121.96746525060358,
 111.92379842780389,
 143.1728240384055,
 141.4132030840501,
 66.99469912410373,
 106.90768299208877,
 94.90911094503619,
 87.41261794799539,
 126.06067034168925,
 130.19111532410787,
 60.165667071440765,
 87.89720090891608,
 84.92622438980145,
 91.

 ### 문제 3.
T시점의 주가를 몬테카를로 시뮬레이션 1000회 시도하여 구하고, 이를 통해 콜옵션가격을 계산하시오.

\begin{align}
S_0 = 100, \ K = 90, \  \sigma = 0.2, \  T = 1, \ r = 0.02 \\
\\
S(T) = S_0 e^{ (r-\frac{\sigma^2}{2})T + \sigma \sqrt{T} \epsilon} \\
\epsilon \sim N(0,1)
\\
\\
C_0^{path(n)} = e^{-rT} \times  Payoff(T)
\\
\\
Payoff(T) = max(S(T) - K, 0)
\\
\\
C_0 = average \ of \ [ C_0^{path1} , C_0^{path2} , C_0^{path3},...,  C_0^{path1000}]
\end{align}

In [29]:
S0, K, sigma , T , r = 100, 90, 0.2, 1, 0.02

In [30]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################
C0_list = []
for i in range(1000) :
    S_path = S0 * np.exp( (r-0.5*sigma**2)*T + sigma * np.sqrt(T) * np.random.normal(0,1) )
    Payoff_T = max ( S_path - K , 0)
    C0 = Payoff_T * np.exp(-r * T)
    C0_list.append(C0)
C = sum(C0_list)/len(C0_list)
C
#############################

15.614741820292421

 ### 문제 4.
T시점의 주가를 몬테카를로 시뮬레이션 1000회 시도하여 구하고, 이를 통해 콜옵션가격을 계산하시오.

블랙숄즈 모형을 통해 콜옵션의 가격을 계산하는 함수를 만드시오.(배당은 없다.)

주가(S), 행사가격(K), 표준편차(sigma), 잔존만기(T), 이자율(r)을 변수로 취급하시오.

또한 문제 4에서 계산한 몬테카를로 시뮬레이션 결과와 블랙숄즈 콜옵션 가격을 비교하시오.

\begin{align}
S_0 = 100, \ K = 90, \  \sigma = 0.2, \  T = 1, \ r = 0.02
\end{align}

<출력화면 예시}

블랙숄즈 : xx원 , 몬테카를로 : xx원

In [31]:
from scipy.stats import norm
S0, K, sigma , T , r = 100, 90, 0.2, 1, 0.02

In [32]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################
C0_list = []
for i in range(1000) :
    S_path = S0 * np.exp( (r-0.5*sigma**2)*T + sigma * np.sqrt(T) * np.random.normal(0,1) )
    Payoff_T = max ( S_path - K , 0)
    C0 = Payoff_T * np.exp(-r * T)
    C0_list.append(C0)
C = sum(C0_list)/len(C0_list)

def Call(S,K,sigma,T,r) :
    d1 = ( np.log(S/K) + (r + 0.5 * sigma**2)*T  ) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    Nd1 = norm.cdf(d1)
    Nd2 = norm.cdf(d2)
    C = S * Nd1 - K * np.exp(-r * T ) * Nd2
    return C

print( '블랙숄즈 : ', Call(S0,K,sigma,T,r) , ', 몬테카를로 : ', C)

#############################

블랙숄즈 :  14.80650701571102 , 몬테카를로 :  15.087841031523238


 ### 문제 5.
T시점의 주가를 몬테카를로 시뮬레이션 1500회 시도하여 구하고, 이를 통해 Binary 콜옵션가격을 계산하시오. Binary 콜옵션은 만기 주가가 행사가격보다 높으면 1원을 주고 그렇지 않으면 0원을 준다.

\begin{align}
S_0 = 100, \ K = 90, \  \sigma = 0.2, \  T = 1, \ r = 0.02 \\
\\
S(T) = S_0 e^{ (r-\frac{\sigma^2}{2})T + \sigma \sqrt{T} \epsilon} \\
\epsilon \sim N(0,1)
\\
\\
C_0^{path(n)} = e^{-rT} \times  Payoff(T)
\\
\\
Payoff(T) = 1 \ \ if \ \ S(T) >= K \ ,\ \  else : \ 0
\\
\\
C_0 = average \ of \ [ C_0^{path1} , C_0^{path2} , C_0^{path3},...,  C_0^{path1000}]
\end{align}

In [33]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################
binary_C0_list = []
for i in range(1500) :
    S_path = S0 * np.exp( (r-0.5*sigma**2)*T + sigma * np.sqrt(T) * np.random.normal(0,1) )
    if S_path >= K :
        Payoff_T = 1
    else :
        Payoff_T = 0
    C0 = Payoff_T * np.exp(-r * T)
    binary_C0_list.append(C0)
binary_C = sum(binary_C0_list)/len(binary_C0_list)
binary_C
#############################

0.6580400426799293

 ### 문제 6.
 블랙숄즈의 Binary 콜옵션 가격은 다음과 같다. 문제 5의 몬테카를로 가격과 비교하시오.
 
 \begin{align}
 C^{binary} = e^{-rT} N(d_2)
 \end{align}

In [34]:
#############################
##풀이과정을 여기에 쓰세요 ##
#############################

def Binary_Call(S,K,sigma,T,r) :
    d1 = ( np.log(S/K) + (r + 0.5 * sigma**2)*T  ) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    Nd2 = norm.cdf(d2)
    C = Nd2 * np.exp(-r * T)
    return C

print(binary_C , Binary_Call(S0,K,sigma,T,r))

#############################


0.6580400426799293 0.686957197925445


 ## 2. Ramdom number generate

In [35]:
import numpy as np

 ### 2-1. basic

In [36]:
np.random.randint(1,100)

74

In [41]:
np.random.randint(1,100) + 100

106

In [42]:
np.random.uniform(1,36,size = 5)

array([34.07594093,  8.52949685,  8.17947547, 31.90179573, 32.48549497])

 ### 2-2. Choice, Sample, Shuffle

In [44]:
my_lst = ['A','C',1,2,3]
np.random.choice(my_lst)

'A'

In [48]:
np.random.choice(my_lst, size = 3, replace = True)

array(['A', '3', 'A'], dtype='<U1')

In [47]:
np.random.choice(my_lst, size = 2, replace = False)

array(['2', 'A'], dtype='<U1')

In [51]:
np.random.shuffle(my_lst)
my_lst

['C', 1, 'A', 2, 3]

 ### 2-3. random normal

In [58]:
np.random.normal(0,1,size = 5) # mu = 0 , sigma = 1

array([1.16641549, 0.1877537 , 0.32025486, 2.11510984, 1.92282514])

In [57]:
np.random.normal(0,1,size = (2,3))

array([[-0.19539939,  1.02572522,  1.51479655],
       [ 0.4340986 , -0.01473762, -1.95321269]])

 ### 2-4. Vectorize

In [15]:
my_lamb = lambda x , y , z  = 0: x+y+z
my_lamb = np.vectorize(my_lamb)

In [16]:
my_lamb(1,2,3), my_lamb(1,2)

(6, 3)

In [17]:
x = np.arange(10)
y = np.arange(10,20)

In [18]:
my_lamb(x,y)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [19]:
xx = np.arange(10).reshape(1,-1)
yy = np.arange(10,20).reshape(-1,1)

In [20]:
my_lamb(xx,yy)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [30]:
xxx = xx.reshape(-1,1,1)
yyy = yy.reshape(1,-1,1)
zzz = np.arange(2).reshape(1,1,-1)

In [42]:
my_lamb(xxx,zzz,yyy)

array([[[10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20]],

       [[11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21]],

       [[12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22]],

       [[13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22],
        [22, 23]],

       [[14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21],
        [21, 22],
        [22, 23],
        [23, 24]],

       [[15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],


 ### 문제 7. 어떤 파생상품의 Payoff는 다음과 같다.
 
 \begin{align}
 Payoff(T) = max(\sqrt{S^1_{(T)} S^2_{(T)}} - 50 , 0)
 \end{align}
 
 S1 = arange(40,80,10)
 
 S2 = arange(35,65,5)
 
 my_payoff = lambda x1, x2 : max(np.sqrt(x1*x2)-50,0)
 
 일 때 만기 Payoff를 2차원으로 나타내시오. 반복문을 사용하지 마시오.

In [41]:
S1_T = np.arange(40,80,10)
S2_T = np.arange(35,65,5)
my_payoff= lambda x1, x2 : max(np.sqrt(x1*x2)-50,0)

In [43]:
###########################
## 풀이과정을 서술하시오. #
###########################
np.vectorize(my_payoff)(S1_T.reshape(-1,1), S2_T.reshape(1,-1))

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  4],
       [ 0,  0,  1,  4,  7, 10],
       [ 0,  2,  6,  9, 12, 14]])